baseURL = 'http://dortort.com/'
languageCode = 'en-us'
title = 'Francis Eytan Dortort'

[params]
  description = "Senior DevSecOps Engineer | Cloud Solutions Architect"
  gtm_id = "GTM-MG75GRFF"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 2

[pagination]
  enabled = true
  pageSize = 10

[markup.goldmark.parser.attribute]
  block = true
  title = true
